DROP TABLE IF EXISTS example.CAMEL_MESSAGEPROCESSED;
DROP TABLE IF EXISTS example.MESSAGES;

CREATE TABLE example.CAMEL_MESSAGEPROCESSED ( 
  processorName VARCHAR(255), 
  messageId VARCHAR(100), 
  createdAt TIMESTAMP
);

CREATE TABLE IF NOT EXISTS example.MESSAGES(
  ID VARCHAR(36) PRIMARY KEY,
  MESSAGE TEXT NOT NULL,
  TS DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);